### ISSUE TITLE
А разве адаптер не предоставляет свой интерфейс для работы с ним по soap? 

### ISSUE THREAD

**Issue by LazarenkoA** [s-sokolko/smev3_adapter_service#1]

**Comment by s-sokolko** [comment]
Добрый день, @LazarenkoA !
Да, всё верно, у адаптера есть интерфейс SOAP, данный проект как раз использует его и предоставляет, в свою очередь, интерфейс для работы по HTTP REST API, что позволяет удобнее и быстрее отправлять запросы в адаптер по SOAP, а также отслеживать результаты выполнения SOAP-запросов
