### ISSUE TITLE
[feature] Предложения по улучшению сервиса

### ISSUE THREAD

**Issue by gosha20777** [s-sokolko/smev3_adapter_service#2]
Спасибо большое за ваш сервис. Я начал разбираться в СМЭВ и Криптопро и ваш сервис многое прояснил для меня. 

Хочу попробовать полностью докеризиовать все компоненты и записать все в `docker-compose` файл.

Сейчас работаю над тем что пытаюсь докеризовать криптопро jcp с СМЭВ адаптером в отдельный докер файл.

У меня есть также опыт работы c Java было бы здорово переписать СМЭВ адаптер на python.
есть ли у вас информация о том где можно взять исходные коды адаптера? я не нашел официального репозитория на github.

p.s. конечно можно "дизасемблировать" jar файлы и восстановить исходный код но хотелось бы пойти более официальным путем и сделать python адаптер для этого.

p.s.s Этот ишшю является не указанием на баг а предложением к сотрудничеству и к улучшению существующей структуры. (Я никогда до этого не работал со СМЭВ и Криптопро и SOAP. И у меня волосы дыбом встают как все тут (я про СМЭВ) реализовано.)

**Comment by s-sokolko** [comment]
Добрый день, @gosha20777 ! 

Благодарю Вас за проявленный интерес к проекту! Любая помощь и участие всячески приветствуются!

На данный момент исходные коды адаптера мне найти не удалось. Есть некая спецификация, которая описывает используемые СМЭВ 3 алгоритмы коммуникации и каноникализации, архитектуру системы. На их базе, в принципе, вполне возможно разработать аналог адаптера СМЭВ 3 от Ростелекома, но на чистом Python. Сложность заключается в том, что необходимо проделать довольно большой объём работы по разработке системы, а также соблюсти все нормы законодательства (например, хранение и использование ЭП по ГОСТ на сертифицированных токенах с помощью криптопровайдера).

Основной открытый ресурс по СМЭВ 3 - это https://smev3.gosuslugi.ru/portal/

Там есть "методические рекомендации" - фактически, это что-то вроде RFC по системе и протоколам. Вот прямая ссылка на документ последней версии https://smev3.gosuslugi.ru/portal/api/files/1_1_%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B5%20%D1%80%D0%B5%D0%BA%D0%BE%D0%BC%D0%B5%D0%BD%D0%B4%D0%B0%D1%86%D0%B8%D0%B8%20%D0%BF%D0%BE%20%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5%20%D1%81%20%D0%95%D0%A1%D0%9C%D0%AD%D0%92%20%D0%B2%D0%B5%D1%80%D1%81%D0%B8%D1%8F%203.5.0.1%20(2)%20(4).docx

**Comment by gosha20777** [comment]
@s-sokolko Благодарю за ответ! Буду разбираться.
