### ISSUE TITLE
No such prefix 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'

### ISSUE THREAD

**Issue by gosha20777** [s-sokolko/smev3_adapter_service#3]
При попытке запуска `run.py` возникает ошибка zeep client:
````python
raise ValueError("No such prefix %r" % prefix)
ValueError: No such prefix 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'
````

**Подробное описание:**

1. Я удалил `mongo-express` сервис из файла [docker-compose.yml](https://github.com/s-sokolko/smev3_adapter_service/blob/master/docker-compose.yml#L15)

2. Модифицировал файл [settings.py](https://github.com/s-sokolko/smev3_adapter_service/blob/master/settings.py):
```python
class Config:
    MONGO_URL = 'mongodb://root:example@localhost:27017/smev_int?authSource=admin'
    ADAPTER_SETTINGS = {
        'url': 'http://localhost:8085/ws?wsdl', # поменял хост смэв адаптера
        'mnemonic': '112233',
        'test_mode': True
    }
    HOST = '0.0.0.0'
    PORT = '9003'
    API_KEY = 'abracadabra'
    API_KEY_HEADER = 'X-Auth-Token'
    RESPONSE_CHECK_TIMEOUT = 60
    DOCUMENT_IDENTIFIERS = {
        'FNSVipUL': 'СвЮЛ.ОГРН',
        'ESIARegister': 'request_id',
        'ESIARegisterCertificate': 'request_id',
    }

```
3. Запустил адаптер СМЭВ-3 на эндпоинте http://localhost:8085.
    3.1 Вошел в панель адаптера СМЭВ-3 как администратор. Добавил Мнемонику 112233 как веб сервис. настроил окружения как тестовое, версии 1.3.
4. Выполнил установку зависимостей: `pip install -r requirements.txt`
5. Запустил mongo db: `docker-compose up`
6. Запустил сервер: `python3 run.py`

Данная ошибка возникает в классе Adapter в конструкторе класса (smev_int/adapter.py):
https://github.com/s-sokolko/smev3_adapter_service/blob/master/smev_int/adapter.py#L41

Конструктор класса вызывается при инициализации сервера (smev_int/core.py):
https://github.com/s-sokolko/smev3_adapter_service/blob/master/smev_int/core.py#L30

Не исключено что это происходит из за моей некорректной настройки СМЭВ-3 адаптера. Было бы здорово получить какой то гайд (задать вам вопросы) по его настройке.

P.s.
Я ознакомился с руководством системного администратора официального портала смэв и выполнил необходимые шаги. Однако я не уверен в правильности всех действий. Также я не очень понимаю откуда брать ключи криптоПро. Я установил JCP и JRE 8 однако не понимаю как заполнить поля блока `подпись`.

Было бы здорово пообщятся с вами напрямую.
Мои контакты:
 - https://vk.com/gosha20777 - ВК (предпочтительный способ)
 - @gosha20777 - telegram (предпочтительный способ)
 - gosha20777@live.ru - email.

**Comment by gosha20777** [comment]
полный стек трейс ошибки:
```python
python3 run.py 
[2019-10-29 13:55:47 +0300] [8122] [DEBUG] 
                 ▄▄▄▄▄
        ▀▀▀██████▄▄▄       _______________
      ▄▄▄▄▄  █████████▄  /                 \
     ▀▀▀▀█████▌ ▀▐▄ ▀▐█ |   Gotta go fast!  |
   ▀▀█████▄▄ ▀██████▄██ | _________________/
   ▀▄▄▄▄▄  ▀▀█▄▀█════█▀ |/
        ▀▀▀▄  ▀▀███ ▀       ▄▄
     ▄███▀▀██▄████████▄ ▄▀▀▀▀▀▀█▌
   ██▀▄▄▄██▀▄███▀ ▀▀████      ▄██
▄▀▀▀▄██▄▀▀▌████▒▒▒▒▒▒███     ▌▄▄▀
▌    ▐▀████▐███▒▒▒▒▒▐██▌
▀▄▄▄▄▀   ▀▀████▒▒▒▒▄██▀
          ▀▀█████████▀
        ▄▄██▀██████▀█
      ▄██▀     ▀▀▀  █
     ▄█             ▐▌
 ▄▄▄▄█▌              ▀█▄▄▄▄▀▀▄
▌     ▐                ▀▀▄▄▄▀
 ▀▀▄▄▀

[2019-10-29 13:55:47 +0300] [8122] [INFO] Goin' Fast @ http://0.0.0.0:9003
http://localhost:8085/ws?wsdl
112233
[2019-10-29 13:55:48 +0300] [8129] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/xsd/schema.py", line 184, in get_ns_prefix
    return self._prefix_map_custom[prefix]
KeyError: 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/xsd/schema.py", line 186, in get_ns_prefix
    return self._prefix_map_auto[prefix]
KeyError: 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gosha20777/.local/lib/python3.6/site-packages/sanic/app.py", line 730, in run
    serve(**server_settings)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/sanic/server.py", line 609, in serve
    trigger_events(before_start, loop)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/sanic/server.py", line 503, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/mnt/e/projects/smev-2-3/smev-3/smev3_adapter_service/smev_int/core.py", line 30, in init_resources
    app.adapter = Adapter(**Config.ADAPTER_SETTINGS)
  File "/mnt/e/projects/smev-2-3/smev-3/smev3_adapter_service/smev_int/adapter.py", line 43, in __init__
    self.factory = self.client.type_factory('urn://x-artefacts-smev-gov-ru/services/service-adapter/types')
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/client.py", line 145, in type_factory
    return Factory(self.wsdl.types, 'type', namespace)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/client.py", line 18, in __init__
    self._ns = types.get_ns_prefix(namespace)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/xsd/schema.py", line 188, in get_ns_prefix
    raise ValueError("No such prefix %r" % prefix)
ValueError: No such prefix 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'
Traceback (most recent call last):
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/xsd/schema.py", line 184, in get_ns_prefix
    return self._prefix_map_custom[prefix]
KeyError: 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/xsd/schema.py", line 186, in get_ns_prefix
    return self._prefix_map_auto[prefix]
KeyError: 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app.run(host=app.Config.HOST, port=app.Config.PORT, debug=True)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/sanic/app.py", line 730, in run
    serve(**server_settings)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/sanic/server.py", line 609, in serve
    trigger_events(before_start, loop)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/sanic/server.py", line 503, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/mnt/e/projects/smev-2-3/smev-3/smev3_adapter_service/smev_int/core.py", line 30, in init_resources
    app.adapter = Adapter(**Config.ADAPTER_SETTINGS)
  File "/mnt/e/projects/smev-2-3/smev-3/smev3_adapter_service/smev_int/adapter.py", line 43, in __init__
    self.factory = self.client.type_factory('urn://x-artefacts-smev-gov-ru/services/service-adapter/types')
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/client.py", line 145, in type_factory
    return Factory(self.wsdl.types, 'type', namespace)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/client.py", line 18, in __init__
    self._ns = types.get_ns_prefix(namespace)
  File "/home/gosha20777/.local/lib/python3.6/site-packages/zeep/xsd/schema.py", line 188, in get_ns_prefix
    raise ValueError("No such prefix %r" % prefix)
ValueError: No such prefix 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types'
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited

```

**Comment by s-sokolko** [comment]
@gosha20777 ошибка, вероятнее всего, связана с тем, что некоторые схемы XSD, предоставляемые на технологическом портале СМЭВ 3 для ряда видов сведений, являются неполными. Мне пришлось копировать куски схемы из методических рекомендаций к некоторым ВС, т.к. там как раз не было чего-то из определения types. Это те файлы, которые помещаются в папку xsd Python-сервиса.

По поводу контактов: создал в нашем официальном сообществе VK тему для обсуждения СМЭВ 3 https://vk.com/topic-164668038_40518373 Это позволит сформировать что-то вроде частых вопросов, которые возникают очень у многих пользователей СМЭВ

**Comment by gosha20777** [comment]
пробую победить смэв.

настроил кприптопро и создал контейнер. Смэв адаптер теперь при запуске валится вот с таким исключением....
(https://vk.com/topic-164668038_40518373) тут полная история с картинками.

> ошибка, вероятнее всего, связана с тем, что некоторые схемы XSD, предоставляемые на технологическом портале СМЭВ 3 для ряда видов сведений, являются неполными.

Но проблема ведь возникает только при инициализации вашего сервиса? Как я понял мы используем xsd только в том случае если шлем сообщение?

1. К нам приходит json мы трансформируем его в xml в соответствии с шаблонами.
2. Мы отправляем xml адаптеру смэв по soap. Он осуществляет обработку, подписывает и шифрует наш запрос и возвращает нам ответ.
3. мы кладем его в базу. и пользователь может забрать его оттуда.

В моем случае вылетает ошибка при самом старте сервиса.

вот так:

`run.py` ->

```python
app.run(host=app.Config.HOST, port=app.Config.PORT, debug=True) #--->
```
`core.py` ->

```python
async def init_resources(app, loop):
    url = Config.MONGO_URL
    client = motor.motor_asyncio.AsyncIOMotorClient(url, io_loop=loop)
    dbname = get_db_from_connstr(url)
    app.mongo = client[dbname]
    app.adapter = Adapter(**Config.ADAPTER_SETTINGS) #--->
    app.asyncio_loop = loop
```

`adapter.py` ->

```python
class Adapter:
    def __init__(self, url, mnemonic, test_mode=False):
        self.test_mode = test_mode
        self.mnemonic = mnemonic
        settings = Settings(strict=False)
        self.client = Client(url, settings=settings)
        # ERROR
        self.factory = self.client.type_factory('urn://x-artefacts-smev-gov-ru/services/service-adapter/types')
```

что делает эта функция (я не не очень хорошо знаю SOAP)?
какие запросы шлет серверу?
что ожидает от него?

я включил отладку смэв адаптера но ничего не увидел в логах...

**Comment by s-sokolko** [comment]
@gosha20777 при запуске smev3_adapter_service пытается установить связь с Адаптером СМЭВ 3 от Ростелекома. Именно оттуда он получает 'urn://x-artefacts-smev-gov-ru/services/service-adapter/types' для создания фабрики типов СМЭВ. Если по URL Адаптера СМЭВ 3 РТК возвращается ошибка, либо некорректное значение, smev3_adapter_service может давать такую ошибку. Попробуйте сделать wget на URL, который передаётся тут

```python
class Adapter:
    def __init__(self, url, mnemonic, test_mode=False):
```

Также рекомендую первым делом запустить сам Адаптер СМЭВ 3 от Ростелеком. Без него не получится протестировать сервис smev3_adapter_service. Более детально настройка адаптера описана у меня в блоге http://xn----jtbajd3aso1dzd.xn--p1ai/blog/%D0%B1%D0%B5%D1%81%D0%BF%D0%BB%D0%B0%D1%82%D0%BD%D1%8B%D0%B9-%D0%B0%D0%B4%D0%B0%D0%BF%D1%82%D0%B5%D1%80-%D1%81%D0%BC%D1%8D%D0%B2-3-%D0%B7%D0%B0%D0%BF%D1%83%D1%81%D0%BA-%D0%B8-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0/

**Comment by gosha20777** [comment]
Спасибо за быстрый ответ. Мне понадобилось время для того чтобы разобраться с адаптером смэв и настроить его работу.

при старте `adapter.py` генерирует следующий запрос:
```xml
GET /ws?wsdl HTTP/1.1
Host: localhost:8085
User-Agent: Zeep/3.2.0 (www.python-zeep.org)
Accept: */*
Connection: keep-alive
Accept-Encoding: gzip, deflate
```
И получает вот такой ответ:
```xml
HTTP/1.1 200 
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Last-Modified: Wed, 10 Jul 2019 11:03:26 GMT
Accept-Ranges: bytes
Content-Type: text/html
Content-Language: ru-RU
Date: Tue, 12 Nov 2019 13:13:53 GMT
Content-Length: 1556

<!DOCTYPE html>
<html ng-app="smevadapter" class="loader">
<head>
    <base href="/">
    <title>СМЭВ Адаптер</title>
    <meta charset="UTF-8">
    <meta http-equiv='Content-Type' content='text/html; charset=UTF-8'/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="favicon.ico"><link href="bundle.54422750f94563892d5f.css" rel="stylesheet"></head>
<body>
<app-component>
    <!-- pre-loader должен быть вне директивы, так как он крутится пока инициализируется приложение -->
    <div class="pre-loader">
        <strong class="logo">СМЭВ АДАПТЕР</strong>
        <div class="throbber-svg">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="92px" height="100px" viewBox="0 0 92 100" enable-background="new 0 0 92 100" xml:space="preserve">
				<path fill="#00aadd" class="throbber-path" d="M81.765,82.649L56.607,97.19c-6.479,3.744-14.462,3.746-20.942,0.01L10.493,82.682
							C4.012,78.944,0.017,72.032,0.014,64.549L0,35.493c-0.003-7.482,3.985-14.398,10.463-18.141L35.621,2.811
							c6.478-3.744,14.46-3.748,20.943-0.011l25.171,14.519c6.481,3.738,10.476,10.648,10.479,18.131l0.014,29.059
							C92.231,71.989,88.244,78.905,81.765,82.649"></path>
            </svg>
        </div>
    </div>
</app-component>
<script type="text/javascript" src="vendor.54422750f94563892d5f.js"></script><script type="text/javascript" src="app.54422750f94563892d5f.js"></script></body>
</html>
```

в этом ответе нет никаких описаний нужных схем. видимо по этому приложение и ломается...

**Comment by s-sokolko** [comment]
@gosha20777 сейчас перенастроил новый адаптер СМЭВ и сервис smev_int. У меня базовая версия из коробки успешно работает с web-service Адаптера Ростелекома на порту 7575

**Comment by gosha20777** [comment]
хм. А какой запрос идет и что приходит в ответ?

Можете воспользоваться программой https://www.ieinspector.com/httpanalyzer/ - она анализирует трафик конкретных приложений. и можно посмотреть какие запросы и куда идут. очень удобная тулза.

**Comment by gosha20777** [comment]
Возможно я как то не так конфигурирую свой адаптер СМЭВ?

Адаптер работает. Несколько раз проверил в режиме "файловое хранилище".

Пробывал запустить его в режимах 
- файловое хранилище
- встроенный интерфейс
- Web интерфейс.

Во всех этих случаях smev3_adapter_service выдаёт ту же самую ошибку. При попытке инициализации. 

Можете ли вы сделать более детальное описание как надо сконфигурировать информационную систему в адаптере СМЭВ? Какие настройки стоят у вас?

Какие запросы шлёт smev3_adapter_service и как адаптер на них отвечает при инициализации? 

Мой smev3_adapter_service настроен по умолчанию. Изменена только мнемонистика и порт адаптера СМЭВ.

**Comment by s-sokolko** [comment]
@gosha20777, к сожалению, дампы и настройки предоставить не можем: там содержатся конфиденциальные данные клиентов. Если Вам необходима индивидуальная поддержка и обучение, можем предложить её на коммерческой основе. Данный продукт является OpenSource-решением и в версии OpenSource предоставляется "как есть".

**Comment by gosha20777** [comment]
Помогли следующие настройки:

1. Настройки конфигурации - показать дополнительные настройки.
2. Перейти во вкладку `7. модули интеграции`. Поставить настройки как на рисунке ниже.

![01](https://user-images.githubusercontent.com/25365364/69047750-f1276e80-0a0c-11ea-8d15-4b0761ab6178.PNG)
*рис 1. настройки модуля интеграции.*

Далее в настройках информационной системы
1. Указать мнемонику 
2. поставить тип интеграции - файловое хранилище.

Эти настройки прописать в `settings.py`

В результате программа должна отработать без ошибок:

```python
Executing <Task finished coro=<init_resources() done, defined at /mnt/e/projects/smev-2-3/smev-3/smev3_adapter_service/smev_int/core.py:24> result=None created at /home/gosha20777/.local/lib/python3.6/site-packages/sanic/server.py:503> took 0.649 seconds
```

**Comment by moiseenko1** [comment]
При отправке сообщения на адаптер (методом Send) возникает исключение Fault. 
![image](https://user-images.githubusercontent.com/48207882/119672205-12a7b880-be43-11eb-9c19-fd98e0cf2e51.png)
